### ISSUE TITLE
../cjax.js file not found error message

### ISSUE THREAD

**Issue by frecervantes** [ajaxboy/cjax#48]
Hi. need help installing Cjax. while I'm on it, i got this messages all the time in the browser.

Not Found
The requested URL /AppServ/www/deliberiusSF/cjax/core/js/cjax.js was not found on this server.
localhost//SITE?test/test2 -->the browser displays a blank page

SOLVED: 
just rename  config.default.php to config.php and 
gave the $config->js_path in this file the path to the cjax.js file ('/mySite/cjax/core/js/').

but now FF says: 
Uncaught TypeError: jQuery.ajaxSetup is not a function
    at Object.CJAX_FRAMEWORK.onStartEvents [as fn] (cjax.js:4739)
    at <anonymous>:9:11
    at r (cjax.js:4670)
    at <anonymous>:1:1

may  you help?

Thanks.

**Comment by HallofFamer** [comment]
This error means you fail to include the jquery lib properly. You need to add a script tag for jquery: 

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
			  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
			  crossorigin="anonymous">
    </script>

Note you must include the entire JQuery, the slim version does not work. I had a similar problem earlier when I installed Bootstrap 4, turned out bootstrap uses JQuery slim by default and I had to change it to the full version so it would work with Cjax.

**Comment by frecervantes** [comment]
thanks HallofFamer
