### ISSUE TITLE
how to call a method from...

### ISSUE THREAD

**Issue by frecervantes** [ajaxboy/cjax#55]
Hi cjax boy,  is it possible to call a method/function from inside a javascript function? if so, how is it? 

regards

**Comment by ajaxboy** [comment]
> Hi cjax boy, is it possible to call a method/function from inside a javascript function? if so, how is it?
> 
> regards

Yes. 

The method is called:
`CJAX.call();`

Look at this documentation 
[http://cjax.sourceforge.net/examples/plugins.php](http://cjax.sourceforge.net/examples/plugins.php)

Under " Plugins JavaScript API "
Look at the area where method `this.call()`  is listed.
You can use any of the methods  listed under that section in inside of your JavaScript. Just instead of using **this** - use CJAX.  eg:  **CJAX.call()**

**Comment by frecervantes** [comment]
thanks very much, forgive to close this issue.
